[package]
name = "zen-office2pdf-jni"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
publish = false

[lib]
name = "zen_office2pdf"
crate-type = ["cdylib"]

[dependencies]
jni = "=0.21.1"
office2pdf = { git = "https://github.com/developer0hye/office2pdf.git", rev = "bb6658bbb66003d0ab5131375acf4daf2f8556a6" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[workspace]

